CREATE TABLE GENERO (
  ID   INT         NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(50) NOT NULL,
  CONSTRAINT PK_GENERO PRIMARY KEY (ID),
  CONSTRAINT UN_NOME UNIQUE (NOME)
);

CREATE TABLE MUSICA (
  ID        INT          NOT NULL AUTO_INCREMENT,
  NOME      VARCHAR(100) NOT NULL,
  ANO       INT          NOT NULL,
  ID_GENERO INT          NOT NULL,
  CONSTRAINT PK_MUSICA PRIMARY KEY (ID),
  CONSTRAINT FK_MUSICA_GENERO FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID)
);

INSERT INTO GENERO(NOME)
VALUES ('Rock'), ('Samba'), ('Funk'), ('Forró'), ('Sertanejo');